"""edit sopcket logs

Revision ID: 0f6b927a6111
Revises: 98eb805187ab
Create Date: 2025-09-01 19:41:13.903681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6b927a6111'
down_revision: Union[str, None] = '98eb805187ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socket_logs', sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
    op.add_column('socket_logs', sa.Column('assigned_doctor_name', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('doctor_assignment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('doctor_assignment_status', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('doctor_assignment_note', sa.Text(), nullable=True))
    op.add_column('socket_logs', sa.Column('assigned_ambulance_id', sa.Integer(), nullable=True))
    op.add_column('socket_logs', sa.Column('assigned_ambulance_driver_name', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('ambulance_assignment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('ambulance_assignment_status', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('ambulance_assignment_note', sa.Text(), nullable=True))
    op.add_column('socket_logs', sa.Column('case_status', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('case_completion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('case_completion_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_socket_logs_ambulance_assignment_date'), 'socket_logs', ['ambulance_assignment_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_assigned_ambulance_id'), 'socket_logs', ['assigned_ambulance_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_assigned_doctor_id'), 'socket_logs', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_case_completion_date'), 'socket_logs', ['case_completion_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_doctor_assignment_date'), 'socket_logs', ['doctor_assignment_date'], unique=False)
    op.create_foreign_key(None, 'socket_logs', 'doctors', ['assigned_doctor_id'], ['id'])
    op.create_foreign_key(None, 'socket_logs', 'ambulances', ['assigned_ambulance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'socket_logs', type_='foreignkey')
    op.drop_constraint(None, 'socket_logs', type_='foreignkey')
    op.drop_index(op.f('ix_socket_logs_doctor_assignment_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_case_completion_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_assigned_doctor_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_assigned_ambulance_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_ambulance_assignment_date'), table_name='socket_logs')
    op.drop_column('socket_logs', 'case_completion_note')
    op.drop_column('socket_logs', 'case_completion_date')
    op.drop_column('socket_logs', 'case_status')
    op.drop_column('socket_logs', 'ambulance_assignment_note')
    op.drop_column('socket_logs', 'ambulance_assignment_status')
    op.drop_column('socket_logs', 'ambulance_assignment_date')
    op.drop_column('socket_logs', 'assigned_ambulance_driver_name')
    op.drop_column('socket_logs', 'assigned_ambulance_id')
    op.drop_column('socket_logs', 'doctor_assignment_note')
    op.drop_column('socket_logs', 'doctor_assignment_status')
    op.drop_column('socket_logs', 'doctor_assignment_date')
    op.drop_column('socket_logs', 'assigned_doctor_name')
    op.drop_column('socket_logs', 'assigned_doctor_id')
    # ### end Alembic commands ###
