"""updated hospital

Revision ID: 23296bcd0614
Revises: 771e89fdb066
Create Date: 2025-08-08 10:19:53.080402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23296bcd0614'
down_revision: Union[str, None] = '771e89fdb066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('emergency_available', sa.Boolean(), nullable=True))
    op.add_column('hospitals', sa.Column('available_24_7', sa.Boolean(), nullable=True))
    op.drop_column('hospitals', 'emergency_24_7')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('emergency_24_7', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hospitals', 'available_24_7')
    op.drop_column('hospitals', 'emergency_available')
    # ### end Alembic commands ###
