"""added_health_data

Revision ID: 29961d96a8b9
Revises: 746fe88e2f9e
Create Date: 2025-08-27 22:39:25.033161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29961d96a8b9'
down_revision: Union[str, None] = '746fe88e2f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('medical_records', sa.Column('addiction', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('smoking', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('drinking', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('medical_records', sa.Column('sugar', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('patient_yes_no', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'patient_yes_no')
    op.drop_column('medical_records', 'sugar')
    op.drop_column('medical_records', 'address')
    op.drop_column('medical_records', 'drinking')
    op.drop_column('medical_records', 'smoking')
    op.drop_column('medical_records', 'addiction')
    op.drop_column('medical_records', 'occupation')
    # ### end Alembic commands ###
