"""updated

Revision ID: 31aac628ab05
Revises: 6f7ae865bd91
Create Date: 2025-07-31 12:47:06.715582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aac628ab05'
down_revision: Union[str, None] = '6f7ae865bd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('admin_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'admin_name')
    # ### end Alembic commands ###
