"""updated patient

Revision ID: 461a62813cfb
Revises: a71d3e2d275a
Create Date: 2025-08-02 16:12:38.931239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461a62813cfb'
down_revision: Union[str, None] = 'a71d3e2d275a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('patients', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'full_name')
    # ### end Alembic commands ###
