"""updated patient

Revision ID: 56f60bc1e29c
Revises: 461a62813cfb
Create Date: 2025-08-02 16:27:00.300721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f60bc1e29c'
down_revision: Union[str, None] = '461a62813cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'phone_number')
    # ### end Alembic commands ###
