"""updated

Revision ID: 6f7ae865bd91
Revises: bf556f90afba
Create Date: 2025-07-30 01:30:25.331081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7ae865bd91'
down_revision: Union[str, None] = 'bf556f90afba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('medical_records_user_id_fkey'), 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('medical_records', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.create_foreign_key(op.f('medical_records_user_id_fkey'), 'medical_records', 'patients', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('medical_records', 'patient_id')
    # ### end Alembic commands ###
