"""add_case_assignments_table

Revision ID: 746fe88e2f9e
Revises: 1d16d715efce
Create Date: 2025-08-21 02:34:54.721293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '746fe88e2f9e'
down_revision: Union[str, None] = '1d16d715efce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socket_logs_accepted_by_hospital_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_created_at'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_event_type'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_hospital_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_socket_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_acceptance_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_expiry_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_rejection_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_status'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_user_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_user_role'), table_name='socket_logs')
    op.drop_table('socket_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socket_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('socket_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('patient_latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sos_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sos_acceptance_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sos_rejection_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sos_expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accepted_by_hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accepted_by_hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_hospital_id'], ['hospitals.id'], name=op.f('socket_logs_accepted_by_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('socket_logs_hospital_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('socket_logs_pkey'))
    )
    op.create_index(op.f('ix_socket_logs_user_role'), 'socket_logs', ['user_role'], unique=False)
    op.create_index(op.f('ix_socket_logs_user_id'), 'socket_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_status'), 'socket_logs', ['sos_status'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_rejection_date'), 'socket_logs', ['sos_rejection_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_expiry_date'), 'socket_logs', ['sos_expiry_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_acceptance_date'), 'socket_logs', ['sos_acceptance_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_socket_id'), 'socket_logs', ['socket_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_hospital_id'), 'socket_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_event_type'), 'socket_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_socket_logs_created_at'), 'socket_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_socket_logs_accepted_by_hospital_id'), 'socket_logs', ['accepted_by_hospital_id'], unique=False)
    # ### end Alembic commands ###
