"""updated hospital

Revision ID: 771e89fdb066
Revises: 7beb32323404
Create Date: 2025-08-08 10:15:57.007431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771e89fdb066'
down_revision: Union[str, None] = '7beb32323404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('hospital_type', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('emergency_24_7', sa.Boolean(), nullable=True))
    op.add_column('hospitals', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('departments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'departments')
    op.drop_column('hospitals', 'registration_number')
    op.drop_column('hospitals', 'emergency_24_7')
    op.drop_column('hospitals', 'hospital_type')
    # ### end Alembic commands ###
