"""updated sos

Revision ID: 7beb32323404
Revises: b803943c962a
Create Date: 2025-08-04 18:36:08.476419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beb32323404'
down_revision: Union[str, None] = 'b803943c962a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add SOS specific fields to socket_logs table
    op.add_column('socket_logs', sa.Column('sos_status', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('sos_acceptance_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('sos_rejection_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('sos_expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socket_logs', sa.Column('accepted_by_hospital_id', sa.Integer(), nullable=True))
    op.add_column('socket_logs', sa.Column('accepted_by_hospital_name', sa.String(), nullable=True))
    op.add_column('socket_logs', sa.Column('rejection_reason', sa.Text(), nullable=True))
    
    # Create indexes for SOS fields
    op.create_index(op.f('ix_socket_logs_sos_status'), 'socket_logs', ['sos_status'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_acceptance_date'), 'socket_logs', ['sos_acceptance_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_rejection_date'), 'socket_logs', ['sos_rejection_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_sos_expiry_date'), 'socket_logs', ['sos_expiry_date'], unique=False)
    op.create_index(op.f('ix_socket_logs_accepted_by_hospital_id'), 'socket_logs', ['accepted_by_hospital_id'], unique=False)
    
    # Add foreign key constraint for accepted_by_hospital_id
    op.create_foreign_key(None, 'socket_logs', 'hospitals', ['accepted_by_hospital_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint
    op.drop_constraint(None, 'socket_logs', type_='foreignkey')
    
    # Drop indexes
    op.drop_index(op.f('ix_socket_logs_accepted_by_hospital_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_expiry_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_rejection_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_acceptance_date'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_sos_status'), table_name='socket_logs')
    
    # Drop SOS specific columns
    op.drop_column('socket_logs', 'rejection_reason')
    op.drop_column('socket_logs', 'accepted_by_hospital_name')
    op.drop_column('socket_logs', 'accepted_by_hospital_id')
    op.drop_column('socket_logs', 'sos_expiry_date')
    op.drop_column('socket_logs', 'sos_rejection_date')
    op.drop_column('socket_logs', 'sos_acceptance_date')
    op.drop_column('socket_logs', 'sos_status')
    
    # ### end Alembic commands ###
