"""added socketlogs

Revision ID: 8e29e3bc63d8
Revises: 46de86ab5d4e
Create Date: 2025-08-02 18:54:34.233394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e29e3bc63d8'
down_revision: Union[str, None] = '46de86ab5d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('socket_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('socket_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('patient_latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospital_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('socket_logs_hospital_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('socket_logs_pkey'))
    )
    op.create_index(op.f('ix_socket_logs_user_role'), 'socket_logs', ['user_role'], unique=False)
    op.create_index(op.f('ix_socket_logs_user_id'), 'socket_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_socket_id'), 'socket_logs', ['socket_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_id'), 'socket_logs', ['id'], unique=False)
    op.create_index(op.f('ix_socket_logs_hospital_id'), 'socket_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_socket_logs_event_type'), 'socket_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_socket_logs_created_at'), 'socket_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socket_logs_created_at'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_event_type'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_hospital_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_socket_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_user_id'), table_name='socket_logs')
    op.drop_index(op.f('ix_socket_logs_user_role'), table_name='socket_logs')
    op.drop_table('socket_logs')
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
