"""added_health_data

Revision ID: 9a3d7795c636
Revises: 29961d96a8b9
Create Date: 2025-08-27 22:49:26.211547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3d7795c636'
down_revision: Union[str, None] = '29961d96a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'patient_yes_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('patient_yes_no', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
