"""edit sopcket logs

Revision ID: ae2c5f4203c4
Revises: 53858353cdcf
Create Date: 2025-09-03 12:19:21.529714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2c5f4203c4'
down_revision: Union[str, None] = '53858353cdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sos_request_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('assignment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('emergency_reason', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('patient_condition', sa.Text(), nullable=True),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('ambulance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_assignment_status', sa.String(length=50), nullable=True),
    sa.Column('ambulance_assignment_status', sa.String(length=50), nullable=True),
    sa.Column('case_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sos_request_id'], ['socket_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assignments_ambulance_assignment_status'), 'patient_assignments', ['ambulance_assignment_status'], unique=False)
    op.create_index(op.f('ix_patient_assignments_ambulance_id'), 'patient_assignments', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_assignment_date'), 'patient_assignments', ['assignment_date'], unique=False)
    op.create_index(op.f('ix_patient_assignments_case_status'), 'patient_assignments', ['case_status'], unique=False)
    op.create_index(op.f('ix_patient_assignments_completed_at'), 'patient_assignments', ['completed_at'], unique=False)
    op.create_index(op.f('ix_patient_assignments_created_at'), 'patient_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_assignments_doctor_assignment_status'), 'patient_assignments', ['doctor_assignment_status'], unique=False)
    op.create_index(op.f('ix_patient_assignments_doctor_id'), 'patient_assignments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_hospital_id'), 'patient_assignments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_id'), 'patient_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_sos_request_id'), 'patient_assignments', ['sos_request_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_status'), 'patient_assignments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_assignments_status'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_sos_request_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_hospital_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_doctor_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_doctor_assignment_status'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_created_at'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_completed_at'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_case_status'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_assignment_date'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_ambulance_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_ambulance_assignment_status'), table_name='patient_assignments')
    op.drop_table('patient_assignments')
    # ### end Alembic commands ###
